### PR TITLE
Added full short syntax to add fields to grid

### PR DESCRIPTION
**Pull request by snovichkov**
Please review my changes and merge them if it possible. I think this method of adding new fields more comfortable.

### CODE REVIEW

**Comment by eliecharra** [comment]
@snovichkov Thanks for your contribution !

Could you please rebase master and add tests to cover this new syntax ?
We will only allow this proper new syntax in future major release, so the doc need to be updated everywhere showing old syntax will be deprecated.

Thxs

**Comment by snovichkov** [comment]
All done. Please review again.

**Comment by eliecharra** [comment]
@snovichkov Could you rebase master on this PR ?
There is a fix in master to correct test failures in TravisCI.

Could you update the readme too with the new syntax and also saying the old is deprecated ?
Thanks you

**Comment by eliecharra** [comment]
Sorry for the delay, will make a release as soon as I can

**Pull request merged**
